# Generated by Django 4.0.4 on 2022-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(upload_to='slideimg')),
            ],
        ),
    ]
