# Generated by Django 4.0.4 on 2022-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='price_tag',
            field=models.ImageField(default='', upload_to='price_tag'),
            preserve_default=False,
        ),
    ]
