# Generated by Django 4.0.4 on 2022-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
