# Generated by Django 4.0.4 on 2022-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image_detail',
            field=models.ImageField(default='', upload_to='productimgdetail'),
            preserve_default=False,
        ),
    ]
