# Generated by Django 4.0.4 on 2022-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sideofferbar',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('sideofferbar', models.ImageField(upload_to='offerimg')),
            ],
        ),
    ]
