# Generated by Django 4.0.4 on 2022-06-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_slider_price_tag'),
        ('website', '0011_reviewrating'),
    ]

    operations = [
    ]
