# Generated by Django 4.0.4 on 2022-06-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
